nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: API allowing clients to access the BileMo product catalog and manage user data.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
