App\Entity\Product:
  product{1..50}:
      name: '<regexify("(iPhone|Galaxy|Pixel|OnePlus|Xperia|Redmi|Mi) [0-9]{1,2}")>'
      brand: '<randomElement(["Apple", "Samsung", "Xiaomi", "Huawei", "OnePlus", "Google", "LG", "Motorola", "Sony", "Nokia"])>'
      price: '<numberBetween(500, 2000)>'
      description: '<paragraph(3)>'
      picture: '<imageUrl(480, 640)>'
      screenSize: '<numberBetween(5, 7)>'
      color: '<randomElement(["Noir", "Blanc", "Rouge", "Bleu", "Vert", "Rose", "Gris", "Jaune", "Orange"])>'
      storageCapacity: '<randomElement(["128", "256", "512"])>'

